const wards = [
  { label: 'Acocks Green', value: 'Acocks Green' },
  { label: 'Allens Cross', value: 'Allens Cross' },
  { label: 'Alum Rock', value: 'Alum Rock' },
  { label: 'Aston', value: 'Aston' },
  { label: 'Balsall Heath West', value: 'Balsall Heath West' },
  { label: 'Bartley Green', value: 'Bartley Green' },
  { label: 'Billesley', value: 'Billesley' },
  { label: 'Birchfield', value: 'Birchfield' },
  { label: 'Bordesley & Highgate', value: 'Bordesley & Highgate' },
  { label: 'Bordesley Green', value: 'Bordesley Green' },
  { label: 'Bournbrook & Selly Park', value: 'Bournbrook & Selly Park' },
  { label: 'Bournville & Cotteridge', value: 'Bournville & Cotteridge' },
  { label: "Brandwood & King's Heath", value: "Brandwood & King's Heath" },
  { label: 'Bromford & Hodge Hill', value: 'Bromford & Hodge Hill' },
  { label: 'Castle Vale', value: 'Castle Vale' },
  { label: 'Druids Heath & Monyhull', value: 'Druids Heath & Monyhull' },
  { label: 'Edgbaston', value: 'Edgbaston' },
  { label: 'Erdington', value: 'Erdington' },
  { label: 'Frankley Great Park', value: 'Frankley Great Park' },
  { label: 'Garretts Green', value: 'Garretts Green' },
  { label: 'Glebe Farm & Tile Cross', value: 'Glebe Farm & Tile Cross' },
  { label: 'Gravelly Hill', value: 'Gravelly Hill' },
  { label: 'Hall Green North', value: 'Hall Green North' },
  { label: 'Hall Green South', value: 'Hall Green South' },
  { label: 'Handsworth', value: 'Handsworth' },
  { label: 'Handsworth Wood', value: 'Handsworth Wood' },
  { label: 'Harborne', value: 'Harborne' },
  { label: 'Heartlands', value: 'Heartlands' },
  { label: "Highter's Heath", value: "Highter's Heath" },
  { label: 'Holyhead', value: 'Holyhead' },
  { label: "King's Norton North", value: "King's Norton North" },
  { label: "King's Norton South", value: "King's Norton South" },
  { label: 'Kingstanding', value: 'Kingstanding' },
  { label: 'Ladywood', value: 'Ladywood' },
  { label: 'Longbridge & West Heath', value: 'Longbridge & West Heath' },
  { label: 'Lozells', value: 'Lozells' },
  { label: 'Moseley', value: 'Moseley' },
  { label: 'Nechells', value: 'Nechells' },
  { label: 'Newtown', value: 'Newtown' },
  { label: 'North Edgbaston', value: 'North Edgbaston' },
  { label: 'Northfield', value: 'Northfield' },
  { label: 'Oscott', value: 'Oscott' },
  { label: 'Perry Barr', value: 'Perry Barr' },
  { label: 'Perry Common', value: 'Perry Common' },
  { label: 'Pype Hayes', value: 'Pype Hayes' },
  { label: 'Quinton', value: 'Quinton' },
  { label: 'Rubery & Rednal', value: 'Rubery & Rednal' },
  { label: 'Shard End', value: 'Shard End' },
  { label: 'Sheldon', value: 'Sheldon' },
  { label: 'Small Heath', value: 'Small Heath' },
  { label: 'Soho & Jewellery Quarter', value: 'Soho & Jewellery Quarter' },
  { label: 'South Yardley', value: 'South Yardley' },
  { label: 'Sparkbrook & Balsall Heath East', value: 'Sparkbrook & Balsall Heath East' },
  { label: 'Sparkhill', value: 'Sparkhill' },
  { label: 'Stirchley', value: 'Stirchley' },
  { label: 'Stockland Green', value: 'Stockland Green' },
  { label: 'Sutton Four Oaks', value: 'Sutton Four Oaks' },
  { label: 'Sutton Mere Green', value: 'Sutton Mere Green' },
  { label: 'Sutton Reddicap', value: 'Sutton Reddicap' },
  { label: 'Sutton Roughley', value: 'Sutton Roughley' },
  { label: 'Sutton Trinity', value: 'Sutton Trinity' },
  { label: 'Sutton Vesey', value: 'Sutton Vesey' },
  { label: 'Sutton Walmley & Minworth', value: 'Sutton Walmley & Minworth' },
  { label: 'Sutton Wylde Green', value: 'Sutton Wylde Green' },
  { label: 'Tyseley & Hay Mills', value: 'Tyseley & Hay Mills' },
  { label: 'Ward End', value: 'Ward End' },
  { label: 'Weoley & Selly Oak', value: 'Weoley & Selly Oak' },
  { label: 'Yardley East', value: 'Yardley East' },
  { label: 'Yardley West & Stechford', value: 'Yardley West & Stechford' },
]
export default wards;